pipeline {
  agent none
  stages {
    stage('Build Java application') {
      steps{
        sh 'javac HelloWorld.java'
      }
    }
    stage('Run Java application') {
      steps{
        sh 'java HelloWorld'
      }
      
    }
  }
}
